import {
	Laptop,
	ShoppingBag,
	PiggyBank,
	BadgePercent,
	ConciergeBell,
	ArrowRightLeft,
	Moon,
	SunMedium,
	Circle,
	DollarSign,
	Home,
	Users,
	Plus,
	Contact,
	Pen,
	Trash,
	MoreHorizontal,
	DoorOpen,
	Store,
	Tag,
	X,
	MenuSquare,
	Eye,
	EyeOff,
	Truck,
	Minus,
	Share,
	Printer,
	Download,
} from "lucide-react";
import {
	TbArrowRight,
	TbBrandGoogle,
	TbCash,
	TbChevronLeft,
	TbDelta,
	TbLoader,
	TbTruck,
} from "react-icons/tb";

export const Icons = {
	spinner: TbLoader,
	google: TbBrandGoogle,
	sun: SunMedium,
	moon: Moon,
	close: X,
	share: Share,
	printer: Printer,
	laptop: Laptop,
	moreHorizontal: MoreHorizontal,
	plus: Plus,
	minus: Minus,
	download: Download,
	logo: TbDelta,
	cash: TbCash,
	bell: ConciergeBell,
	trash: Trash,
	pen: Pen,
	eye: Eye,
	eyeOff: EyeOff,
	circle: Circle,
	dollar: DollarSign,
	home: Home,
	persons: Users,
	store: Store,
	badgePercent: BadgePercent,
	employee: Contact,
	tag: Tag,
	truck: Truck,
	doorOpen: DoorOpen,
	transaction: ArrowRightLeft,
	menu: MenuSquare,
	chevronLeft: TbChevronLeft,
	shoppigBag: ShoppingBag,
	arrowRight: TbArrowRight,
	piggyBank: PiggyBank,
};
